# Generated by Django 5.1.5 on 2025-03-22 15:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomendapeca',
            name='referencia_fornecedor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referência do Fornecedor'),
        ),
        migrations.AddField(
            model_name='encomendapeca',
            name='referencia_interna',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referência Interna'),
        ),
        migrations.AddField(
            model_name='historicalencomendapeca',
            name='referencia_fornecedor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referência do Fornecedor'),
        ),
        migrations.AddField(
            model_name='historicalencomendapeca',
            name='referencia_interna',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Referência Interna'),
        ),
        migrations.AlterField(
            model_name='encomendapeca',
            name='data_encomenda',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Encomenda'),
        ),
        migrations.AlterField(
            model_name='historicalencomendapeca',
            name='data_encomenda',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data da Encomenda'),
        ),
    ]
