# Generated by Django 5.1.5 on 2025-03-22 15:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_encomendapeca_referencia_fornecedor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peca',
            name='fornecedores',
        ),
        migrations.AddField(
            model_name='historicalpeca',
            name='unidade',
            field=models.CharField(default='un', max_length=20, verbose_name='Unidade'),
        ),
        migrations.AddField(
            model_name='peca',
            name='unidade',
            field=models.CharField(default='un', max_length=20, verbose_name='Unidade'),
        ),
        migrations.AlterField(
            model_name='historicalpeca',
            name='codigo',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='historicalpeca',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='historicalpeca',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='historicalpeca',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.categoriapeca', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='codigo',
            field=models.CharField(max_length=50, unique=True, verbose_name='Código Interno'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='localizacao',
            field=models.CharField(blank=True, max_length=100, verbose_name='Localização'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='nome',
            field=models.CharField(max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='peca',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Mínimo'),
        ),
        migrations.CreateModel(
            name='FornecedorPeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia_fornecedor', models.CharField(max_length=100, verbose_name='Referência do Fornecedor')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('tempo_entrega', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo Médio de Entrega (dias)')),
                ('preco_ultima_atualizacao', models.DateField(auto_now=True, verbose_name='Data Última Atualização de Preço')),
                ('fornecedor_preferencial', models.BooleanField(default=False, verbose_name='Fornecedor Preferencial')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pecas_fornecidas', to='stock.fornecedor', verbose_name='Fornecedor')),
                ('peca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores', to='stock.peca', verbose_name='Peça')),
            ],
            options={
                'verbose_name': 'Fornecedor de Peça',
                'verbose_name_plural': 'Fornecedores de Peças',
                'unique_together': {('fornecedor', 'peca')},
            },
        ),
        migrations.AddField(
            model_name='historicalitemencomenda',
            name='fornecedor_peca',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.fornecedorpeca', verbose_name='Referência do Fornecedor'),
        ),
        migrations.AddField(
            model_name='historicalmovimentacaostock',
            name='fornecedor_peca',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.fornecedorpeca', verbose_name='Referência do Fornecedor'),
        ),
        migrations.AddField(
            model_name='itemencomenda',
            name='fornecedor_peca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_encomenda', to='stock.fornecedorpeca', verbose_name='Referência do Fornecedor'),
        ),
        migrations.AddField(
            model_name='movimentacaostock',
            name='fornecedor_peca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='stock.fornecedorpeca', verbose_name='Referência do Fornecedor'),
        ),
        migrations.CreateModel(
            name='HistoricalFornecedorPeca',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('referencia_fornecedor', models.CharField(max_length=100, verbose_name='Referência do Fornecedor')),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço Unitário')),
                ('tempo_entrega', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tempo Médio de Entrega (dias)')),
                ('preco_ultima_atualizacao', models.DateField(blank=True, editable=False, verbose_name='Data Última Atualização de Preço')),
                ('fornecedor_preferencial', models.BooleanField(default=False, verbose_name='Fornecedor Preferencial')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('fornecedor', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.fornecedor', verbose_name='Fornecedor')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('peca', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='stock.peca', verbose_name='Peça')),
            ],
            options={
                'verbose_name': 'historical Fornecedor de Peça',
                'verbose_name_plural': 'historical Fornecedores de Peças',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
