# Generated by Django 5.1.5 on 2025-02-10 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria de Equipamento',
                'verbose_name_plural': 'Categorias de Equipamentos',
            },
        ),
        migrations.CreateModel(
            name='EquipamentoFabricado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('referencia_interna', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('especificacoes', models.TextField(blank=True, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='equipamentos/fotos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.categoriaequipamento')),
            ],
        ),
        migrations.CreateModel(
            name='EquipamentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='clientes.cliente')),
                ('equipamento_fabricado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='equipamentos.equipamentofabricado')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos_equipamentos/')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='equipamentos.equipamentofabricado')),
            ],
        ),
    ]
