# Generated by Django 5.1.5 on 2025-04-11 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', 'add_category_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaequipamento',
            options={'ordering': ['nome'], 'verbose_name': 'Categoria de Equipamento', 'verbose_name_plural': 'Categorias de Equipamento'},
        ),
        migrations.AddField(
            model_name='categoriaequipamento',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoriaequipamento',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
