# Generated by Django 5.1.5 on 2025-04-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_alter_categoriaequipamento_options_and_more'),
        ('equipamentos', 'add_ativo_field'),
    ]

    operations = [
    ]
