# Generated by Django 5.1.5 on 2025-02-10 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_alter_equipamentofabricado_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoequipamento',
            name='titulo',
        ),
        migrations.AddField(
            model_name='documentoequipamento',
            name='nome',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='documentoequipamento',
            name='arquivo',
            field=models.FileField(upload_to='documentos_equipamento/'),
        ),
    ]
