# Generated by Django 5.1.5 on 2025-04-15 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0002_merge_20250411_1325'),
        ('equipamentos', 'add_timestamps_to_categoria'),
    ]

    operations = [
    ]
