# Generated by Django 5.1.5 on 2025-02-10 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0003_remove_documentoequipamento_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentoequipamento',
            name='nome',
        ),
    ]
