# Generated by Django 5.1.5 on 2025-02-13 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0003_alter_pedidoassistencia_equipamento'),
        ('equipamentos', '0004_remove_documentoequipamento_nome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EquipamentoCliente',
        ),
    ]
