# Generated by Django 5.1.5 on 2025-04-15 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0004_merge_20250415_1002'),
    ]

    operations = [
    ]
