# Generated by Django 5.1.5 on 2025-02-13 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_delete_equipamentocliente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoriaequipamento',
            options={},
        ),
        migrations.RemoveField(
            model_name='equipamentofabricado',
            name='foto',
        ),
        migrations.AddField(
            model_name='equipamentofabricado',
            name='fotografia',
            field=models.ImageField(blank=True, null=True, upload_to='equipamentos_fotos/'),
        ),
        migrations.AlterField(
            model_name='documentoequipamento',
            name='arquivo',
            field=models.FileField(upload_to='equipamentos_documentos/'),
        ),
        migrations.AlterField(
            model_name='equipamentofabricado',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='equipamentos.categoriaequipamento'),
        ),
    ]
