# Generated by Django 5.1.5 on 2025-04-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0005_auto_20250415_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriaequipamento',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='categoriaequipamento',
            name='icone',
        ),
        migrations.AlterField(
            model_name='categoriaequipamento',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
    ]
