# Generated by Django 5.1.5 on 2025-04-17 08:49

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_cargo_remove_cliente_categoria_and_more'),
        ('equipamentos', '0006_remove_categoriaequipamento_cor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de transferência')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Motivo')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_history', to='equipamentos.equipamentocliente', verbose_name='Equipamento')),
                ('new_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_equipment', to='clientes.cliente', verbose_name='Novo cliente')),
                ('previous_client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_equipment', to='clientes.cliente', verbose_name='Cliente anterior')),
            ],
            options={
                'verbose_name': 'Registro de transferência',
                'verbose_name_plural': 'Registros de transferências',
                'ordering': ['-transfer_date'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalEquipamentoCliente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente')),
                ('equipamento_fabricado', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipamentos.equipamentofabricado')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical equipamento cliente',
                'verbose_name_plural': 'historical equipamento clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
