# Generated by Django 5.1.5 on 2025-03-30 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistencia', '0001_initial'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedidoassistencia',
            name='cliente',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='historicalpedidoassistencia',
            name='equipamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.equipamentocliente', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='historicalpedidoassistencia',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicopat',
            name='utilizador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pats', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pats', to='clientes.equipamentocliente', verbose_name='Equipamento'),
        ),
        migrations.AddField(
            model_name='itempat',
            name='pat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='assistencia.pedidoassistencia', verbose_name='PAT'),
        ),
        migrations.AddField(
            model_name='historicopat',
            name='pat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='assistencia.pedidoassistencia'),
        ),
        migrations.AddField(
            model_name='historicalitempat',
            name='pat',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='assistencia.pedidoassistencia', verbose_name='PAT'),
        ),
        migrations.AddIndex(
            model_name='pedidoassistencia',
            index=models.Index(fields=['estado', 'data_entrada'], name='assistencia_estado_51823a_idx'),
        ),
        migrations.AddIndex(
            model_name='pedidoassistencia',
            index=models.Index(fields=['cliente', 'estado'], name='assistencia_cliente_ffbac6_idx'),
        ),
        migrations.AddIndex(
            model_name='itempat',
            index=models.Index(fields=['pat', 'tipo'], name='assistencia_pat_id_bb4a4b_idx'),
        ),
        migrations.AddIndex(
            model_name='itempat',
            index=models.Index(fields=['referencia'], name='assistencia_referen_7712bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='itempat',
            constraint=models.CheckConstraint(condition=models.Q(('quantidade__gt', 0)), name='quantidade_positiva'),
        ),
        migrations.AddConstraint(
            model_name='itempat',
            constraint=models.CheckConstraint(condition=models.Q(('preco__gte', 0)), name='preco_nao_negativo'),
        ),
    ]
