# Generated by Django 5.1.5 on 2025-04-02 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0002_initial'),
        ('equipamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpedidoassistencia',
            name='equipamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipamentos.equipamentocliente', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pats', to='equipamentos.equipamentocliente', verbose_name='Equipamento'),
        ),
    ]
