# Generated by Django 5.1.5 on 2025-04-02 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamentos', '0001_initial'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnota',
            name='equipamento',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipamentos.equipamentocliente', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_equipamento', to='equipamentos.equipamentocliente', verbose_name='Equipamento'),
        ),
    ]
