# Generated by Django 5.1.5 on 2025-02-10 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('equipamentos', '0004_remove_documentoequipamento_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAssistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.CharField(max_length=50, unique=True)),
                ('garantia', models.BooleanField(default=False)),
                ('data_entrada', models.DateField()),
                ('data_conclusao', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Recebida', 'Recebida'), ('Em Diagnóstico', 'Em Diagnóstico'), ('Em Curso', 'Em Curso'), ('Concluída', 'Concluída')], default='Recebida', max_length=20)),
                ('descricao_problema', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_assistencia', to='clientes.cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_assistencia', to='equipamentos.equipamentocliente')),
            ],
        ),
    ]
