# Generated by Django 5.1.5 on 2025-02-18 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoAssistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pat_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número da PAT')),
                ('data_entrada', models.DateField(verbose_name='Data de Entrada')),
                ('estado', models.CharField(choices=[('aberto', 'Aberto'), ('em_curso', 'Em Curso'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('em_diagnostico', 'Em Diagnóstico')], default='aberto', max_length=20, verbose_name='Estado da PAT')),
                ('relatorio', models.TextField(blank=True, null=True, verbose_name='Relatório')),
                ('garantia', models.BooleanField(default=False, help_text='Marque se o equipamento estiver em garantia.', verbose_name='Em Garantia')),
                ('data_reparacao', models.DateField(blank=True, null=True, verbose_name='Data de Reparação')),
                ('data_criacao', models.DateField(null=True, verbose_name='Data de Criação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pats', to='clientes.cliente', verbose_name='Cliente')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pats', to='clientes.equipamentocliente', verbose_name='Equipamento')),
            ],
        ),
        migrations.CreateModel(
            name='ItemPat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servico', 'Serviço'), ('componente', 'Componente')], max_length=20, verbose_name='Tipo')),
                ('referencia', models.CharField(max_length=100, verbose_name='Referência')),
                ('designacao', models.CharField(max_length=255, verbose_name='Designação')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='assistencia.pedidoassistencia', verbose_name='PAT')),
            ],
        ),
    ]
