# Generated by Django 5.1.5 on 2025-04-16 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0001_initial'),
        ('clientes', '0002_remove_cliente_cargo_remove_cliente_categoria_and_more'),
        ('equipamentos', '0006_remove_categoriaequipamento_cor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitempat',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalitempat',
            name='pat',
        ),
        migrations.RemoveField(
            model_name='historicalpedidoassistencia',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='historicalpedidoassistencia',
            name='equipamento',
        ),
        migrations.RemoveField(
            model_name='historicalpedidoassistencia',
            name='history_user',
        ),
        migrations.AlterModelOptions(
            name='historicopat',
            options={'ordering': ['-data_registo'], 'verbose_name': 'Histórico de PAT', 'verbose_name_plural': 'Históricos de PAT'},
        ),
        migrations.AlterModelOptions(
            name='itempat',
            options={'verbose_name': 'Item de PAT', 'verbose_name_plural': 'Itens de PAT'},
        ),
        migrations.AlterModelOptions(
            name='pedidoassistencia',
            options={'ordering': ['-data_criacao'], 'verbose_name': 'Pedido de Assistência Técnica', 'verbose_name_plural': 'Pedidos de Assistência Técnica'},
        ),
        migrations.RemoveConstraint(
            model_name='itempat',
            name='quantidade_positiva',
        ),
        migrations.RemoveConstraint(
            model_name='itempat',
            name='preco_nao_negativo',
        ),
        migrations.RemoveIndex(
            model_name='itempat',
            name='assistencia_pat_id_bb4a4b_idx',
        ),
        migrations.RemoveIndex(
            model_name='itempat',
            name='assistencia_referen_7712bb_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidoassistencia',
            name='assistencia_estado_51823a_idx',
        ),
        migrations.RemoveIndex(
            model_name='pedidoassistencia',
            name='assistencia_cliente_ffbac6_idx',
        ),
        migrations.RemoveField(
            model_name='historicopat',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='historicopat',
            name='estado_anterior',
        ),
        migrations.RemoveField(
            model_name='historicopat',
            name='estado_novo',
        ),
        migrations.RemoveField(
            model_name='historicopat',
            name='utilizador',
        ),
        migrations.RemoveField(
            model_name='itempat',
            name='data_entrada',
        ),
        migrations.RemoveField(
            model_name='itempat',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='itempat',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='pedidoassistencia',
            name='data_reparacao',
        ),
        migrations.RemoveField(
            model_name='pedidoassistencia',
            name='data_ultima_transferencia',
        ),
        migrations.RemoveField(
            model_name='pedidoassistencia',
            name='garantia',
        ),
        migrations.RemoveField(
            model_name='pedidoassistencia',
            name='proprietario_atual',
        ),
        migrations.RemoveField(
            model_name='pedidoassistencia',
            name='proprietario_original',
        ),
        migrations.RemoveField(
            model_name='pedidoassistencia',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='historicopat',
            name='descricao',
            field=models.TextField(default='non', verbose_name='Descrição'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicopat',
            name='tipo',
            field=models.CharField(choices=[('status', 'Mudança de Status'), ('note', 'Observação'), ('item', 'Item Adicionado/Removido')], default='Componente', max_length=20, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicopat',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itempat',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço Unitário'),
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Atualização'),
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='data_conclusao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Conclusão'),
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='descricao_problema',
            field=models.TextField(default='none', verbose_name='Descrição do Problema'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='tecnico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pats_atribuidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='itempat',
            name='designacao',
            field=models.CharField(max_length=200, verbose_name='Designação'),
        ),
        migrations.AlterField(
            model_name='itempat',
            name='pat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='assistencia.pedidoassistencia'),
        ),
        migrations.AlterField(
            model_name='itempat',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='itempat',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referência'),
        ),
        migrations.AlterField(
            model_name='itempat',
            name='tipo',
            field=models.CharField(choices=[('peca', 'Peça'), ('servico', 'Serviço'), ('componente', 'Componente')], default='peca', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pats', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='equipamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pats', to='equipamentos.equipamentocliente'),
        ),
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='estado',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_diagnostico', 'Em Diagnóstico'), ('em_andamento', 'Em Andamento'), ('aguardando_peca', 'Aguardando Peça'), ('aguardando_cliente', 'Aguardando Cliente'), ('concluido', 'Concluído')], default='aberto', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='numero_serie_equipamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série do Equipamento'),
        ),
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='pat_number',
            field=models.CharField(max_length=50, unique=True, verbose_name='Número PAT'),
        ),
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='relatorio',
            field=models.TextField(blank=True, null=True, verbose_name='Relatório Técnico'),
        ),
        migrations.DeleteModel(
            name='HistoricalItemPat',
        ),
        migrations.DeleteModel(
            name='HistoricalPedidoAssistencia',
        ),
    ]
