# Generated by Django 5.1.5 on 2025-02-10 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidoassistencia',
            old_name='data_conclusao',
            new_name='data_reparacao',
        ),
        migrations.RenameField(
            model_name='pedidoassistencia',
            old_name='garantia',
            new_name='em_garantia',
        ),
    ]
