# Generated by Django 5.1.5 on 2025-04-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0002_remove_historicalitempat_history_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempat',
            options={'verbose_name': 'Item PAT', 'verbose_name_plural': 'Itens PAT'},
        ),
        migrations.AlterField(
            model_name='itempat',
            name='designacao',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='itempat',
            name='preco_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempat',
            name='quantidade',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itempat',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itempat',
            name='tipo',
            field=models.CharField(choices=[('peca', 'Peça'), ('servico', 'Serviço'), ('componente', 'Componente'), ('outro', 'Outro')], default='peca', max_length=10),
        ),
    ]
