# Generated by Django 5.1.5 on 2025-02-13 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0002_rename_data_conclusao_pedidoassistencia_data_reparacao_and_more'),
        ('clientes', '0002_remove_cliente_data_criacao_remove_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_assistencia', to='clientes.equipamentocliente'),
        ),
    ]
