# Generated by Django 5.1.5 on 2025-02-19 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0003_alter_pedidoassistencia_pat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempat',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
