# Generated by Django 5.1.5 on 2025-04-17 08:49

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0003_alter_itempat_options_alter_itempat_designacao_and_more'),
        ('clientes', '0002_remove_cliente_cargo_remove_cliente_categoria_and_more'),
        ('equipamentos', '0006_remove_categoriaequipamento_cor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='estado',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_diagnostico', 'Em Diagnóstico'), ('em_andamento', 'Em Andamento'), ('aguardando_peca', 'Aguardando Peça'), ('aguardando_cliente', 'Aguardando Cliente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=50, verbose_name='Estado'),
        ),
        migrations.CreateModel(
            name='HistoricalPedidoAssistencia',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pat_number', models.CharField(db_index=True, max_length=50, verbose_name='Número PAT')),
                ('numero_serie_equipamento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série do Equipamento')),
                ('data_entrada', models.DateField(default=django.utils.timezone.now, verbose_name='Data de Entrada')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Atualização')),
                ('data_conclusao', models.DateField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('estado', models.CharField(choices=[('aberto', 'Aberto'), ('em_diagnostico', 'Em Diagnóstico'), ('em_andamento', 'Em Andamento'), ('aguardando_peca', 'Aguardando Peça'), ('aguardando_cliente', 'Aguardando Cliente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], default='aberto', max_length=50, verbose_name='Estado')),
                ('descricao_problema', models.TextField(verbose_name='Descrição do Problema')),
                ('relatorio', models.TextField(blank=True, null=True, verbose_name='Relatório Técnico')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('cliente', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente')),
                ('equipamento', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipamentos.equipamentocliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tecnico', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pedido de Assistência Técnica',
                'verbose_name_plural': 'historical Pedidos de Assistência Técnica',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('aberto', 'Aberto'), ('em_diagnostico', 'Em Diagnóstico'), ('em_andamento', 'Em Andamento'), ('aguardando_peca', 'Aguardando Peça'), ('aguardando_cliente', 'Aguardando Cliente'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado')], max_length=30, verbose_name='Estado')),
                ('data_alteracao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de alteração')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='assistencia.pedidoassistencia')),
            ],
            options={
                'verbose_name': 'Histórico de Status',
                'verbose_name_plural': 'Históricos de Status',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
