# Generated by Django 5.1.5 on 2025-02-18 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0003_alter_pedidoassistencia_equipamento'),
        ('clientes', '0004_alter_equipamentocliente_numero_serie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoassistencia',
            name='descricao_problema',
        ),
        migrations.RemoveField(
            model_name='pedidoassistencia',
            name='em_garantia',
        ),
        migrations.RemoveField(
            model_name='pedidoassistencia',
            name='numero_pedido',
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='data_criacao',
            field=models.DateField(null=True, verbose_name='Data de Criação'),
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='garantia',
            field=models.BooleanField(default=False, help_text='Marque se o equipamento estiver em garantia.', verbose_name='Em Garantia'),
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='pat_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Número da PAT'),
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='relatorio',
            field=models.TextField(blank=True, null=True, verbose_name='Relatório'),
        ),
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pats', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='data_entrada',
            field=models.DateField(verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='data_reparacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Reparação'),
        ),
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pats', to='clientes.equipamentocliente', verbose_name='Equipamento'),
        ),
        migrations.AlterField(
            model_name='pedidoassistencia',
            name='estado',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('em_curso', 'Em Curso'), ('concluido', 'Concluído'), ('cancelado', 'Cancelado'), ('em_diagnostico', 'Em Diagnóstico')], default='aberto', max_length=20, verbose_name='Estado da PAT'),
        ),
        migrations.CreateModel(
            name='ItemPat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('servico', 'Serviço'), ('componente', 'Componente')], max_length=20, verbose_name='Tipo')),
                ('referencia', models.CharField(max_length=100, verbose_name='Referência')),
                ('designacao', models.CharField(max_length=255, verbose_name='Designação')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='assistencia.pedidoassistencia', verbose_name='PAT')),
            ],
        ),
    ]
