# Generated by Django 5.1.6 on 2025-03-25 17:02

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0003_historicalitempat_historicalpedidoassistencia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalitempat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='historicalpedidoassistencia',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='itempat',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pedidoassistencia',
            name='created_at',
        ),
        migrations.AddField(
            model_name='historicalitempat',
            name='data_entrada',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalpedidoassistencia',
            name='data_criacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 3, 25, 17, 1, 11, 891726, tzinfo=datetime.timezone.utc), editable=False, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itempat',
            name='data_entrada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='HistoricoPAT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registo', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registo')),
                ('estado_anterior', models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado Anterior')),
                ('estado_novo', models.CharField(max_length=50, verbose_name='Estado Novo')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='Comentário')),
                ('pat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='assistencia.pedidoassistencia')),
                ('utilizador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de PAT',
                'verbose_name_plural': 'Históricos de PAT',
            },
        ),
    ]
