# Generated by Django 5.1.5 on 2025-03-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0004_remove_historicalitempat_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpedidoassistencia',
            name='data_ultima_transferencia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Transferência'),
        ),
        migrations.AddField(
            model_name='historicalpedidoassistencia',
            name='numero_serie_equipamento',
            field=models.CharField(blank=True, help_text='Preserva o número de série mesmo que o equipamento seja transferido', max_length=100, verbose_name='Número de Série (histórico)'),
        ),
        migrations.AddField(
            model_name='historicalpedidoassistencia',
            name='proprietario_atual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Proprietário Atual'),
        ),
        migrations.AddField(
            model_name='historicalpedidoassistencia',
            name='proprietario_original',
            field=models.CharField(blank=True, max_length=255, verbose_name='Proprietário Original'),
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='data_ultima_transferencia',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da Última Transferência'),
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='numero_serie_equipamento',
            field=models.CharField(blank=True, help_text='Preserva o número de série mesmo que o equipamento seja transferido', max_length=100, verbose_name='Número de Série (histórico)'),
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='proprietario_atual',
            field=models.CharField(blank=True, max_length=255, verbose_name='Proprietário Atual'),
        ),
        migrations.AddField(
            model_name='pedidoassistencia',
            name='proprietario_original',
            field=models.CharField(blank=True, max_length=255, verbose_name='Proprietário Original'),
        ),
    ]
