# Generated by Django 5.1.5 on 2025-02-27 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0004_itempat_quantidade'),
        ('clientes', '0001_initial'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('status', models.CharField(choices=[('a_fazer', 'A Fazer'), ('concluido', 'Concluído')], default='a_fazer', max_length=10, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='clientes.cliente', verbose_name='Cliente')),
                ('equipamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='clientes.equipamentocliente', verbose_name='Equipamento')),
                ('pat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas', to='assistencia.pedidoassistencia', verbose_name='PAT')),
            ],
        ),
        migrations.DeleteModel(
            name='NotaConversa',
        ),
    ]
