# Generated by Django 5.1.5 on 2025-02-28 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notas', '0002_nota_delete_notaconversa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='status',
        ),
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[('a_fazer', 'A Fazer'), ('concluido', 'Concluído')], default='a_fazer', max_length=10, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='notas.nota')),
            ],
        ),
    ]
