# Generated by Django 5.1.5 on 2025-02-28 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistencia', '0004_itempat_quantidade'),
        ('clientes', '0001_initial'),
        ('notas', '0003_remove_nota_status_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='cliente',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='clientes.cliente', verbose_name='Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarefa',
            name='pat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas', to='assistencia.pedidoassistencia', verbose_name='PAT'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='nota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='notas.nota', verbose_name='Nota'),
        ),
    ]
