# Generated by Django 5.1.5 on 2025-03-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_empresa', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='config/logos/')),
                ('cor_primaria', models.CharField(default='#4e73df', help_text='Código de cor hexadecimal', max_length=7)),
                ('cor_secundaria', models.CharField(default='#1cc88a', help_text='Código de cor hexadecimal', max_length=7)),
                ('tema', models.CharField(choices=[('default', 'Padrão'), ('dark', 'Escuro'), ('light', 'Claro')], default='default', max_length=20)),
                ('clientes_por_pagina', models.PositiveIntegerField(default=25)),
                ('permitir_cadastro_duplicado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
            },
        ),
    ]
