# Generated by Django 5.1.5 on 2025-04-02 14:13

import django.db.models.deletion
import django_countries.fields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('icone', models.CharField(blank=True, help_text='Classe CSS para ícone (ex: fa-envelope)', max_length=50, null=True, verbose_name='Ícone')),
                ('validador_regex', models.CharField(blank=True, help_text='Expressão regular para validar o valor', max_length=255, null=True, verbose_name='Validador RegEx')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Contacto',
                'verbose_name_plural': 'Tipos de Contacto',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='clientes/imagens/')),
                ('website', models.URLField(blank=True, null=True)),
                ('email_principal', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('individual', 'Individual')], default='empresa', max_length=15)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('nif', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF/VAT')),
                ('percentagem_iva', models.DecimalField(decimal_places=2, default=23.0, max_digits=5)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, help_text='Desconto padrão em percentagem', max_digits=5)),
                ('morada', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', django_countries.fields.CountryField(blank=True, default='PT', max_length=2, null=True)),
                ('usar_mesma_morada', models.BooleanField(default=True, help_text='Usar a mesma morada para entrega')),
                ('morada_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal_entrega', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('pais_entrega', django_countries.fields.CountryField(blank=True, default='PT', max_length=2, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.categoriacliente')),
                ('empresa_associada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('imagem', models.TextField(blank=True, max_length=100, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email_principal', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('individual', 'Individual')], default='empresa', max_length=15)),
                ('cargo', models.CharField(blank=True, max_length=100, null=True)),
                ('nif', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF/VAT')),
                ('percentagem_iva', models.DecimalField(decimal_places=2, default=23.0, max_digits=5)),
                ('desconto', models.DecimalField(decimal_places=2, default=0.0, help_text='Desconto padrão em percentagem', max_digits=5)),
                ('morada', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade', models.CharField(blank=True, max_length=100, null=True)),
                ('pais', django_countries.fields.CountryField(blank=True, default='PT', max_length=2, null=True)),
                ('usar_mesma_morada', models.BooleanField(default=True, help_text='Usar a mesma morada para entrega')),
                ('morada_entrega', models.CharField(blank=True, max_length=255, null=True)),
                ('codigo_postal_entrega', models.CharField(blank=True, max_length=20, null=True)),
                ('cidade_entrega', models.CharField(blank=True, max_length=100, null=True)),
                ('pais_entrega', django_countries.fields.CountryField(blank=True, default='PT', max_length=2, null=True)),
                ('data_criacao', models.DateTimeField(blank=True, editable=False)),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.categoriacliente')),
                ('empresa_associada', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'verbose_name_plural': 'historical Clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor')),
                ('nome_contacto', models.CharField(blank=True, help_text='Nome da pessoa de contacto (se aplicável)', max_length=100, null=True, verbose_name='Nome')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.cliente')),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.tipocontacto', verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-principal', 'tipo', 'valor'],
            },
        ),
    ]
