# Generated by Django 5.1.5 on 2025-03-30 03:06

import django.db.models.deletion
import django_countries.fields
import simple_history.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('individual', 'Individual')], max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('imagem', models.ImageField(blank=True, help_text='Logo para empresas ou foto para individuais', null=True, upload_to='clientes/', verbose_name='Imagem')),
                ('nif', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF')),
                ('regime_iva', models.CharField(choices=[('normal', 'Normal'), ('isento', 'Isento'), ('reduzido', 'Reduzido')], default='normal', max_length=20, verbose_name='Regime de IVA')),
                ('desconto_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto Padrão (%)')),
                ('morada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Morada')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('pais', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='País')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCliente',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('individual', 'Individual')], max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Website')),
                ('imagem', models.TextField(blank=True, help_text='Logo para empresas ou foto para individuais', max_length=100, null=True, verbose_name='Imagem')),
                ('nif', models.CharField(blank=True, max_length=20, null=True, verbose_name='NIF')),
                ('regime_iva', models.CharField(choices=[('normal', 'Normal'), ('isento', 'Isento'), ('reduzido', 'Reduzido')], default='normal', max_length=20, verbose_name='Regime de IVA')),
                ('desconto_padrao', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Desconto Padrão (%)')),
                ('morada', models.CharField(blank=True, max_length=255, null=True, verbose_name='Morada')),
                ('codigo_postal', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('pais', django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='País')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(blank=True, editable=False, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(blank=True, editable=False, verbose_name='Última Atualização')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'verbose_name_plural': 'historical Clientes',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='InteracaoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('ligacao', 'Ligação'), ('email', 'Email'), ('reuniao', 'Reunião'), ('visita', 'Visita'), ('outro', 'Outro')], max_length=50, null=True, verbose_name='Tipo')),
                ('data', models.DateTimeField(auto_now_add=True, verbose_name='Data')),
                ('assunto', models.CharField(blank=True, max_length=200, null=True, verbose_name='Assunto')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Interação com Cliente',
                'verbose_name_plural': 'Interações com Clientes',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='TarefaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_limite', models.DateTimeField(blank=True, null=True, verbose_name='Data Limite')),
                ('prioridade', models.CharField(choices=[('baixa', 'Baixa'), ('media', 'Média'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20, verbose_name='Prioridade')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
            ],
            options={
                'verbose_name': 'Tarefa de Cliente',
                'verbose_name_plural': 'Tarefas de Clientes',
                'ordering': ['concluida', 'data_limite'],
            },
        ),
        migrations.CreateModel(
            name='TipoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('icone', models.CharField(blank=True, help_text='Classe CSS para ícone (ex: fa-envelope)', max_length=50, null=True, verbose_name='Ícone')),
                ('validador_regex', models.CharField(blank=True, help_text='Expressão regular para validar o valor', max_length=255, null=True, verbose_name='Validador RegEx')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Contacto',
                'verbose_name_plural': 'Tipos de Contacto',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.cliente')),
                ('nome_comercial', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Comercial')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
            bases=('clientes.cliente',),
        ),
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('cliente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='clientes.cliente')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Individual',
                'verbose_name_plural': 'Individuais',
            },
            bases=('clientes.cliente',),
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Valor')),
                ('nome_contacto', models.CharField(blank=True, help_text='Nome da pessoa de contacto (se aplicável)', max_length=100, null=True, verbose_name='Nome')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('principal', models.BooleanField(default=False, verbose_name='Principal')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Contacto',
                'verbose_name_plural': 'Contactos',
                'ordering': ['-principal', 'tipo', 'valor'],
            },
        ),
        migrations.CreateModel(
            name='EquipamentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('data_instalacao', models.DateField(blank=True, null=True, verbose_name='Data de Instalação')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Equipamento de Cliente',
                'verbose_name_plural': 'Equipamentos de Clientes',
            },
        ),
    ]
