# Generated by Django 5.1.5 on 2025-03-30 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('equipamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamentocliente',
            name='equipamento_fabricado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clientes_equipamentos', to='equipamentos.equipamentofabricado'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='interacaocliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='interacoes', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='interacaocliente',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interacoes_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='setor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.setor', verbose_name='Setor de Atividade'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.setor', verbose_name='Setor de Atividade'),
        ),
        migrations.AddField(
            model_name='tarefacliente',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_clientes', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='tarefacliente',
            name='responsavel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_cliente', to=settings.AUTH_USER_MODEL, verbose_name='Responsável'),
        ),
        migrations.AddField(
            model_name='contacto',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clientes.tipocontacto', verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='individual',
            name='empresa_associada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='colaboradores', to='clientes.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='equipamentocliente',
            unique_together={('cliente', 'equipamento_fabricado', 'numero_serie')},
        ),
    ]
