# Generated by Django 5.1.5 on 2025-04-03 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='empresa_associada',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='empresa_associada',
        ),
        migrations.RemoveField(
            model_name='historicalcliente',
            name='tipo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.setor', verbose_name='Setor de Atividade'),
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='setor',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clientes.setor', verbose_name='Setor de Atividade'),
        ),
    ]
