# Generated by Django 5.1.5 on 2025-02-13 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('equipamentos', '0004_remove_documentoequipamento_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.CreateModel(
            name='EquipamentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipamentos', to='clientes.cliente')),
                ('equipamento_fabricado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamentos.equipamentofabricado')),
            ],
        ),
    ]
