# Generated by Django 5.1.5 on 2025-02-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_endereco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamentocliente',
            name='numero_serie',
            field=models.CharField(error_messages={'unique': 'Este número de série já está associado a outro equipamento e/ou cliente.'}, max_length=100, unique=True),
        ),
    ]
